### ISSUE TITLE
Request authorization to blog about this

### ISSUE THREAD

**Issue by JorgePe** [iConor/lego-lirc#1]
Hi!
I was googling for a way to use LIRC to control Power Functions IR and found your lego-lirc repository.
I'm using an homemade IR transmitter (2 LED's connected to the audio output jack of my laptop) and with your config files I already can spin a motor, thank you very much!!!

I know it sounds strange to use audio card as a remote controller but I don't have anything USB-based and I need somthing that works seamless in my laptop (Ubuntu), in a Raspberry Pi (Debian) and a LEGO Mindstorms EV3 (with a USB audio card and running ev3dev, also Debian).

I searched for more info about this but found nothing, you don't have a blog or something do you?
I would like to post your conf files in my blog and link to here, is it OK?

Best regards,
Jorge

**Comment by iConor** [comment]
Absolutely! It's great to hear someone found this useful!

On my setup the LED is connected to a Raspberry Pi via the GPIO's, but I'll have to check out this audio jack method when your blog post is up. It'd be nice to mess around with it directly from my laptop.

I originally had a blog post explaining how I was using it but the whole blog died in a fire at the beginning of the semester. I'll look for the backups, or my original notes, and see about getting the README into a useful state.

**Comment by JorgePe** [comment]
Thanks!! Just give me some hours, I'll send you the link very soon.

**Comment by JorgePe** [comment]
Here goes. I still need to make a video demo but the essencial is there.
http://ofalcao.pt/blog/2014/infrared-remote-control
Feel free to comment and if you don't like the way I refer to you or your work please do say so, I'll change it.
Thanks again.
